### PR TITLE
[UI] Bugfix the unused volume health status should be none

### LINKED ISSUE #2902: The unused/unbound volumes should not in healthy status.
**Component**: ui

**What happened**:
For the unused/unbound volume, it is in **healthy** state with green circle.
image

**What was expected**:
Since the volume is not bound, so we don't have PVC, then no monitoring. So we can't get any alerts, but it doesn't mean it's healthy.  

**Steps to reproduce**
Create a new volume.

**Resolution proposal** (optional):
Set **none** health state for the unused volumes (A circle without filled color)
image
Improvement:
We should give a message in the Alerts tab, saying that "No alert because the volume is unused"
image

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: ui, bugs

**Context**: 
Since the volume is not bound, so we don't have PVC, then no monitoring. So we can't get any alerts, but it doesn't mean it's healthy.

**Summary**:
- Set none health state for the unused volumes (A circle without filled color)
- For unbound volume, display "The volume is not bound yet" in the alerts tab

**Acceptance criteria**: 
image
image

---

Closes: #2902

### CODE REVIEW

File: ui/src/services/NodeVolumesUtils.js [hunk 1]
```diff
@@ -211,23 +211,23 @@ export const getVolumeListData = createSelector(
...
-        )
-          ? STATUS_CRITICAL
-          : STATUS_WARNING;
-      } else if (volumeComputedCondition === ('exclamation' || 'unlink')) {
-        volumeHealth = STATUS_NONE;
+        // THE RULES TO COMPUTE THE HEALTH
+        // compute the volume health based on the severity of the alerts
+        // critical => if there is at least one critical
+        if (volumeAlerts.length) {
+          volumeHealth = volumeAlerts.find(
```
Comment (slaperche-scality) [inline ui/src/services/NodeVolumesUtils.js]: nitpick: instead of using `find`, I would rather use [`some`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some).

> The some() method tests whether at least one element in the array passes the test implemented by the provided function. It returns a Boolean value. 

Reason being: you don't want to **find** the first critical alert (i.e you don't care about the alert object itself), you only want to know if there are **some** critical alerts in the array.
=> it's more logical to use `some` than `find`.

Comment (ChengYanJin) [reply ui/src/services/NodeVolumesUtils.js]: Thanks Sylvain!! It definitely makes sense, we just need a Boolean to tell us if there is a critical alert.

**Review by thomasdanan — DISMISSED** [review]
I am okay with the new behaviour

**Review by thomasdanan — APPROVED** [review]
