### PR TITLE
Split classes to handle different kind of packages

### LINKED ISSUE #1472: integrate sos-report and calico-cni debian packages
**Component**: package

**Why this is needed**: Because Alien doesn't work for sos-report to convert it to a rpm to deb package

**What should be done**: 
- create sos-report debian source 
- integrate it in the buildchain
- modify the buildchain to build the sources
- modify the buildchain to convert calico

**Implementation proposal** (strongly recommended):

- [x] Split packages for debian packages integration

- [x] Split the repository class to handle Debian & RedHat repo separatly

- [x]  modify docker calls to use a specify entrypoint script  in depending of the os family 

- [x]  Correct the path of sos-resources  sources used in the mounted volum to build it in Debian  package

- [x]  integrate Debian package builder classes in the top level to permit to use them

- [x]  Modify entrypoint to build & convert packages

**Test plan**: verify that calico is well installed

### PR DESCRIPTION
**Pull request by ycointe**
**Component**: Buildchain, package

**Context**: Metalk8s on Ubuntu

**Summary**: We need to to split some classes in the buildchain to integrate Debian and build its packages.

**Acceptance criteria**: 
- classes separated
- Build still available 
- Centos cluster deployment available

---

Closes: #1472

### CODE REVIEW

File: packages/debian/entrypoint.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
+#!/bin/bash
+
+set -e
+set -u
+set -o pipefail
+
+rpm2deb() {
+	set -x
+	chown build:build /home/build
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Why chowning the home directory, the ownership should already be right, no ?

File: packages/debian/entrypoint.sh [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+	cp -p /rpmbuild/SRC/*.deb /debbuild/PKG
+	chown "${TARGET_UID}:${TARGET_GID}" \
+		/debbuild/DEBS/*
+}
+
+builddeb() {
+	#need to be done with user "build"
+	set -x
+	chown build:build /home/build
+        pushd /debbuild/PKG 1>/dev/null
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Why moving in this directory since the line just after you use a full path and right after you move again ?
For me, this line is useless, must be a leftover of a copy/paste from your function above.

File: packages/debian/entrypoint.sh [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+set -e
+set -u
+set -o pipefail
+
+rpm2deb() {
+	set -x
+	chown build:build /home/build
+	pushd /debbuild/PKG 1>/dev/null
+	for RPM in /rpmbuild/SRC/calico*.rpm; do
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Should be based on a list of packages to alienize, not hardcoded.

File: packages/debian/entrypoint.sh [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+builddeb() {
+	#need to be done with user "build"
+	set -x
+	chown build:build /home/build
+        pushd /debbuild/PKG 1>/dev/null
+	for DEBSRC in /debbuild/PKG; do
+		pushd /debbuild/PKG/metalk8s-sosreport/debian
+		debuild -b -uc -us
+	done
+	cp -p /debbuild/SRC/* /debbuild/PKG
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Not really an error, but is there any good reason for using `-p` ? (just for my personal understanding)

File: packages/debian/entrypoint.sh [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+	chown "${TARGET_UID}:${TARGET_GID}" \
+		/debbuild/DEBS/*
+}
+
+builddeb() {
+	#need to be done with user "build"
+	set -x
+	chown build:build /home/build
+        pushd /debbuild/PKG 1>/dev/null
+	for DEBSRC in /debbuild/PKG; do
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Will not work, you need to use a wildcard:
```
for debsrc in /debbuild/PKG/*; do
```
And conventionally, you use lowercased variable when the purpose of the variable is local.
Uppercase is reserved for global variables.

File: packages/debian/entrypoint.sh [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+		pushd /debbuild/PKG/metalk8s-sosreport/debian
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Hardcoded package name, you're not using the variable set before `$DEBSRC`

File: packages/debian/entrypoint.sh [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+	done
+	cp -p /rpmbuild/SRC/*.deb /debbuild/PKG
+	chown "${TARGET_UID}:${TARGET_GID}" \
+		/debbuild/DEBS/*
+}
+
+builddeb() {
+	#need to be done with user "build"
+	set -x
+	chown build:build /home/build
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Same as above

File: packages/debian/entrypoint.sh [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+        pushd /debbuild/PKG 1>/dev/null
+	for DEBSRC in /debbuild/PKG; do
+		pushd /debbuild/PKG/metalk8s-sosreport/debian
+		debuild -b -uc -us
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Need to be run as build user:
```
su build -c "debuild -b -uc -us"
```

File: packages/debian/entrypoint.sh [hunk 9]
```diff
@@ -0,0 +1,31 @@
...
+set -o pipefail
+
+rpm2deb() {
+	set -x
+	chown build:build /home/build
+	pushd /debbuild/PKG 1>/dev/null
+	for RPM in /rpmbuild/SRC/calico*.rpm; do
+		alien --bump=0 "$RPM"
+	done
+	cp -p /rpmbuild/SRC/*.deb /debbuild/PKG
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Useless as you already moved to `/debbuild/PKG` before your loop and the result files (*.deb) from alien are generated in the current directory.

File: packages/debian/entrypoint.sh (hunk 1 above)
Comment (ycointe) [reply packages/debian/entrypoint.sh]: Indeed, It was more a kind of "security" to be sur. I delete it.

File: packages/debian/entrypoint.sh (hunk 4 above)
Comment (ycointe) [reply packages/debian/entrypoint.sh]: It was to "preserve" rights on its but no, it was not very needed because of the `chown` applied after.

File: packages/debian/entrypoint.sh (hunk 8 above)
Comment (ycointe) [reply packages/debian/entrypoint.sh]: Not necessary, i prefer to use a `chown` after which will apply another owner that `root`.

File: buildchain/buildchain/targets/package.py [hunk 10]
```diff
@@ -319,3 +320,114 @@ def _file_from_url(url: str) -> str:
...
+        builder: image.ContainerImage,
+        **kwargs: Any
+    ):
+        super().__init__(
+            basename, name, version, build_id, builder,
+            constants.PKG_DEB_ROOT, **kwargs
+         )
+        self._sources = sources
+
+    sources = property(operator.attrgetter('_sources'))
```
Comment (jbertran) [inline buildchain/buildchain/targets/package.py:346]: I think that with a little work the `sources` management can me mutualized into the `Package` class. This can be an improvement ticket I guess.

E: ~~most likely we want to tend towards the current RPM behaviour, where it would be easy to specify 2 different source paths whereas this would be a problem in the current DEB behaviour.~~ after discussion with @slaperche-scality , just create a debt ticket for reworking/rewording the `sources` thing - it turns out I didn't understand it fully but we still have an issue with it.

File: buildchain/buildchain/targets/package.py [hunk 11]
```diff
@@ -319,3 +320,114 @@ def _file_from_url(url: str) -> str:
...
+    @property
+    def execution_plan(self) -> List[types.TaskDict]:
+        tasks = [self.make_package_directory()]
+        if self.sources.suffix == '.rpm':
+            tasks.append(self.convert_package())
+        else:
+            tasks.append(self.build_deb_package())
+        return tasks
+
+    def build_deb_package(self) -> types.TaskDict:
```
Comment (jbertran) [inline buildchain/buildchain/targets/package.py]: Can be renamed `build_package` like the `RPMPackage` equivalent.

**Review by jbertran — COMMENTED** [review]
Dayum, dayum, dayum.

LGTM. Great work!

File: packages/debian/entrypoint.sh [hunk 12]
```diff
@@ -0,0 +1,52 @@
...
+    cp -r /debbuild/pkg-meta/* /debbuild/build-pkg
+    cp -r /debbuild/pkg-src/* /debbuild/build-pkg/src
+
+    # Overwrite version if supported
+    sed -i 's/_VERSION_/'"${VERSION}"'/g' "/debbuild/build-pkg/debian/changelog"
+
+    pushd /debbuild/build-pkg 1>/dev/null
+    debuild -b -uc -us
+
+    cp -r /debbuild/*.deb /debbuild/result
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Not sure you need `-r`, except if you're trying to copy directories named `*.deb`. :)

File: packages/debian/entrypoint.sh [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+}
+
+
+# Build a DEB from an RPM file, using alien.
+rpm2deb() {
+    set -x
+
+    alien --bump=0 /rpmbuild/source.rpm
+
+    cp /*.deb /debbuild/result
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: And what about:
```
pushd /debbuild/result 1> /dev/null
alien --bump=0 /rpmbuild/source.rpm
chown "$TARGET_UID:$TARGET_GID" *
```

File: packages/debian/entrypoint.sh [hunk 14]
```diff
@@ -0,0 +1,52 @@
...
+    chown -R "${TARGET_UID}:${TARGET_GID}" /debbuild/result
+}
+
+
+case ${1:-''} in
```
Comment (alexandre-allard) [inline packages/debian/entrypoint.sh]: Details: Useless quotes, but it does not hurt, I think. :)

File: packages/debian/entrypoint.sh (hunk 12 above)
Comment (ycointe) [reply packages/debian/entrypoint.sh]: nop, indeed! :) 
Thanks

File: buildchain/buildchain/targets/package.py (hunk 10 above)
Comment (ycointe) [reply buildchain/buildchain/targets/package.py:346]: I create a ticket, you can follow the issue REF #1623

File: packages/debian/entrypoint.sh (hunk 14 above)
Comment (ycointe) [reply packages/debian/entrypoint.sh]: Change for Debian and RedHat entrypoint :)

**Comment by ycointe** [comment]
@bert-e approve

**Review by jbertran — APPROVED** [review]
