### PR TITLE
Check that solution archive path is valid

### LINKED ISSUE #3267: Running `solutions.sh import` with a non-existent directory in the archive path exits without any message
**Component**: scripts, solutions

**What happened**:

- Running `./solutions.sh import -a /existent-dir/non-existent.iso` properly returns:

```
> Updating Solutions configuration file... fail [0s]

Failure while running step 'Updating Solutions configuration file'

Command: configure_archives

Output:

<< BEGIN >>
File '/existent-dir/non-existent.iso' is not an ISO archive
<< END >>

This script will now exit
```

- Running `./solutions.sh import -a /non-existent-dir/non-existent.iso` improperly exits (rc=1) without any output.

**What was expected**:

Both situations should behave similarly, with clear output for the user to troubleshoot.

### PR DESCRIPTION
**Pull request by alexandre-allard**
**Component**: scripts, solutions

**Context**: 
When trying to import a solution providing a non-existing path, the solutions.sh script exit in error with no output.

**Summary**:
Ensure the provided archive path exists and exit in error, with a clear message, if not.

**Acceptance criteria**:

---

Closes: #3267

### CODE REVIEW

File: scripts/solutions.sh [hunk 1]
```diff
@@ -138,7 +138,12 @@ while :; do
     case $1 in
         -a|--archive)
             shift
-            ARCHIVES+=("$(readlink -f "$1")")
+            ARCHIVE_ABS_PATH=$(readlink -f "$1" ||:)
```
Comment (gdemonet) [inline scripts/solutions.sh]: What does `||:` do?

Comment (alexandre-allard) [reply scripts/solutions.sh]: `|| true` if you prefer (I can change it), it allows to ignore the non-zero exit code from readlink otherwise the script exits since we use `set -e`.

Comment (alexandre-allard) [reply scripts/solutions.sh]: Changed this for a clearer approach.

File: scripts/solutions.sh [hunk 2]
```diff
@@ -138,6 +138,10 @@ while :; do
     case $1 in
         -a|--archive)
             shift
+            if [ ! -e "$1" ]; then
+                echo 1>&2 "No such file or directory '$1'"
+                exit 1
+            fi
             ARCHIVES+=("$(readlink -f "$1")")
```
Comment (gdemonet) [inline scripts/solutions.sh:145]: What if the link exists but doesn't resolve? Is `test -e` checking this?

**Review by gdemonet — APPROVED** [review]

File: scripts/solutions.sh (hunk 2 above)
Comment (alexandre-allard) [reply scripts/solutions.sh:145]: You mean if the link points to non-existing file or directory ?
The check fails.
