### PR TITLE
ui/bug: fix the bug when there is no PV && add unit test for isVolumeDeletable

### LINKED ISSUE #1673: Impossible to delete a volume in status failed
**Component**:
Volume Web GUI management

**What happened**:
I created a volume and the creation has failed. I would like to remove it using the GUI but, first the tips is empty and second when I click on the trash bin nothing happen.

If I list my current pv with kubectl it doesn't appeared in the list. The information seems to be only in the GUI db.

**What was expected**:
Being able to remove it to recreate it with the same name.

**Steps to reproduce**
Create a raw block device with a wrong device name it will fail.

**Resolution proposal** (optional):

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: ui

**Context**: 
When the volume is failed, if there is no PV found, the volume is not deletable.

**Summary**:
Fix the bug.
Add a unit test for `isVolumeDeletable` function in NodeVolumes. 
There are in total of 17 cases with the different combinations of volume and PV.

**Acceptance criteria**: 
Pass all the 17 cases

Closes: #1673

### CODE REVIEW

File: ui/src/containers/NodeVolumes.js [hunk 1]
```diff
@@ -119,7 +119,7 @@ const NodeVolumes = props => {
     setSortDirection(sortDirection);
   };
 
-  const isVolumeDeletable = rowData => {
+  const isVolumeDeletable = (rowData, persistentVolumes) => {
```
Comment (slaperche-scality) [inline ui/src/containers/NodeVolumes.js]: Why do we need this change?

Before we were already using `persistentVolumes` l.136, it wasn't working?

File: ui/src/containers/NodeVolumesUtils.js [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+  STATUS_UNKNOWN,
+  STATUS_TERMINATING,
+  STATUS_PENDING,
+  STATUS_FAILED,
+  STATUS_AVAILABLE,
+  STATUS_BOUND,
+  STATUS_RELEASED,
+} from '../constants';
+
+export const isVolumeDeletable = (rowData, persistentVolumes) => {
```
Comment (slaperche-scality) [inline ui/src/containers/NodeVolumesUtils.js]: This seems copied from `ui/src/containers/NodeVolumes.js`, is it normal to keep two versions of the same code?

If the goal is to make the function usable in the test, I guess `ui/src/containers/NodeVolumes.js` should use this version as well (so that the code tested is the one used for real).

Comment (carlito-scality) [inline ui/src/containers/NodeVolumesUtils.js]: Where do you use it?

**Review by carlito-scality — CHANGES_REQUESTED** [review]

File: ui/src/containers/NodeVolumesUtils.js (hunk 2 above)
Comment (carlito-scality) [reply ui/src/containers/NodeVolumesUtils.js]: As discussed before, please put it in 'services' folder instead of 'containers'.

File: ui/src/containers/NodeVolumesUtils.test.js [hunk 3]
```diff
@@ -0,0 +1,256 @@
+import { isVolumeDeletable } from './NodeVolumesUtils';
+
+const testcase1 = {
```
Comment (slaperche-scality) [inline ui/src/containers/NodeVolumesUtils.test.js]: We probably could have more meaningful name that `testcaseX`, `testcaseY`, …

- `testcase1` => `testcaseVolumeWithoutStatus`
- `testcase2` => `testcaseVolumePending`
- `testcase3` => `testcaseVolumeTerminating`
- `testcase4` => `testcaseVolumeFailedWithoutPv`
- `testcase5` => `testcaseVolumeFailedWithPvFailed`
- […]
- `testcase11` => `testcaseVolumeAvailableWithPvFailed`
- […]
- `testcase17` => testcaseVolumeAvailableWithoutPv

**Review by slaperche-scality — COMMENTED** [review]
I think we could have 2 commits here:
- one for the bugfix
- one for the tests

Also, I don't know much about JS tests frameworks, but maybe there is some way to have less boilerplate here.

**Review by MonPote — APPROVED** [review]

**Review by carlito-scality — APPROVED** [review]

**Comment by ChengYanJin** [comment]
@bert-e approve
