### PR TITLE
ui: Bugfix several bug fixes around cluster version create volume 

### LINKED ISSUE #3303: ui: Volume creation : button add for labels should change from disable to enable status when a label value and key is provided
**Component**:

UI

**Why this is needed**:

From a ux point of view it is not enough evident that we have to click `add` button when having entered the label, leading to human error creating the volume without the label despite having filled it in.

image

**What should be done**:

We should change the status of the button once having provided a label key and value so that the user clearly see the required action.

**Test plan**:

Unit test

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: ui

**Context**: 
Bugfix:
1. When the size is `Unknown` no need to add a unit
2. Add the color of `create` button in create node & volume page to `buttonPrimary`
3. Fix the cluster version in create node page
4. Add about entry from the Navbar
5. Fix the display bug of labels in crate volume page
6. Add default `ui_base_path` in `config.json`
7.  Translations 
8. After deleting a volume, redirect to the first volume - overview tab
9. Fix the error when a new node is not ready, we can receive the string from ipInterfaceObject

Improvement:
10. Merge the label validation before creating a new volume and **improve the UX of creating volume**
- when the label key and value are valid, the `Add` button will become enabled, otherwise stay disable.

image

**Summary**:

**Acceptance criteria**: 

---

Closes: #3303  
Closes: #3328
Closes: #3203

### CODE REVIEW

File: ui/src/containers/CreateVolume.js [hunk 1]
```diff
@@ -568,14 +570,25 @@ const CreateVolume = (props) => {
...
+                              variant={'buttonSecondary'}
+                            />
+                          ) : (
+                            <Button
+                              text={intl.translate('add')}
+                              type="button"
+                              onClick={addLabel}
+                              data-cy="add-volume-labels-button"
+                              outlined
+                            />
```
Comment (JBWatenbergScality) [inline ui/src/containers/CreateVolume.js]: shouldn't we disable the button initially instead of just changing it's color ? Also I think we can remove the onClick handler in this case

File: ui/src/services/salt/api.js [hunk 2]
```diff
@@ -68,10 +68,36 @@ export type IPInterfaces = {
...
+            "127.0.0.1",
+            "::1"
+          ],
+          "eth0": [
+            "10.200.6.201",
+            "fe80::f816:3eff:fec3:b710"
+          ]
+        }
+      },
+      "toto": "Minion did not return. [No response]\nThe minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:\n\nsalt-run jobs.lookup_jid 20210429184803777520"
```
Comment (JBWatenbergScality) [inline ui/src/services/salt/api.js]:
```suggestion
      "nodeName": "Minion did not return. [No response]\nThe minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:\n\nsalt-run jobs.lookup_jid 20210429184803777520"
```

File: ui/src/containers/CreateVolume.js (hunk 1 above)
Comment (ChengYanJin) [reply ui/src/containers/CreateVolume.js]: Done in https://github.com/scality/metalk8s/pull/3338/commits/7a961e20d30abe2e3ea76d4d7050fbe7bc9464c4 ;)

**Review by JBWatenbergScality — DISMISSED** [review]

File: ui/src/containers/CreateVolume.js [hunk 3]
```diff
@@ -435,13 +453,64 @@ const CreateVolume = (props) => {
                   }
                 }
               };
+              // TODO: Apply this function as `labelName` field validation function, for the moment we only have one error message.
```
Comment (JBWatenbergScality) [inline ui/src/containers/CreateVolume.js]: Is this todo still valid ? I see various error message in the implementation.

Comment (ChengYanJin) [reply ui/src/containers/CreateVolume.js]: OK. So in the end I switched to `Field-level Validation` instead of `Yup` schema which will display the error message separately for the `label prefix` and `labe name value`.
Please see: https://github.com/scality/metalk8s/pull/3338/commits/9917a17a96db87f73451d6d13ff38e6b7db8de77

File: ui/src/containers/CreateVolume.js [hunk 4]
```diff
@@ -453,64 +455,40 @@ const CreateVolume = (props) => {
...
-              // TODO: Apply this function as `labelName` field validation function, for the moment we only have one error message.
-              const handleErrorLabel = () => {
-                const isLabelNameMatched = labelFullNameRegex.test(
-                  values.labelName,
-                );
-                const isLabelValueMatched = labelValueRegex.test(
-                  values.labelValue,
-                );
 
+              const validataLabelName = (value) => {
```
Comment (JBWatenbergScality) [inline ui/src/containers/CreateVolume.js:459]: validateLabelName

File: ui/cypress/fixtures/kubernetes/storageclasses.json [hunk 5]
```diff
@@ -0,0 +1,207 @@
+{
+  "apiVersion": "storage.k8s.io/v1",
+  "items": [
```
Comment (JBWatenbergScality) [inline ui/cypress/fixtures/kubernetes/storageclasses.json:3]: I would limit the storage classes only to the one that makes sense for our tests

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+
+// interaction test for creating volume
+describe('the create button in create volume page', () => {
+  it('should be enabled and the Add button should be disabled when no labels is specified', () => {
+    cy.get('input[name=name]').type(VOLUME_NAME);
+
+    cy.get('.sc-select').eq(0).click();
+    cy.get('.sc-select__menu').eq(0).click();
+    cy.get('.sc-select').eq(1).click();
+    cy.get('.sc-select__menu')
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: We should avoid dom selectors by classnames and tests this as user interact with. With the current implementation the most elegant solution is to look for elements with text matching /node*/i and click on the next `.sc-select`. Ideally we should add an aria role with listbox value on the dropdown component https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role + an aria-label with value "node"

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+      .find(`[data-cy=storageClass-${STORAGECLASS}]`)
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: We should select the element via the text presented to the user

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+      .click();
+    cy.get('.sc-select').eq(2).click();
+    cy.get('.sc-select__menu').find(`[data-cy="type-${VOLUME_TYPE}"]`).click();
+    cy.get('input[name=sizeInput]').type(VOLUME_SIZE);
+
+    cy.get('[data-cy="submit-create-volume"]').should('be.enabled');
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: use cy.queryByRole('button', {name: /create/i})

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+    cy.get('[data-cy="add-volume-labels-button"]').should('be.disabled');
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: use cy.queryByRole('button', {name: /add/i})

File: ui/cypress/fixtures/kubernetes/storageclasses.json (hunk 5 above)
Comment (ChengYanJin) [reply ui/cypress/fixtures/kubernetes/storageclasses.json:3]: OK. I was hesitating should I keep only one storage class. I will do so then.

File: ui/cypress/integration/volume/createvolume.spec.js (hunk 9 above)
Comment (ChengYanJin) [reply ui/cypress/integration/volume/createvolume.spec.js]: Just FYI in case you miss it :)
https://github.com/testing-library/cypress-testing-library/releases/tag/v6.0.0
so should be: `  cy.findByRole('button', { name: /create/i })`

File: ui/cypress/integration/volume/createvolume.spec.js (hunk 7 above)
Comment (ChengYanJin) [reply ui/cypress/integration/volume/createvolume.spec.js]: In the end, we got to keep the `data-cy`, the reason is:

>   /* we use `data-cy`is because the storageClass may display in both the select list and selected item, 
>      so we use unique selector to make sure to choose the item in the list. */

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 10]
```diff
@@ -0,0 +1,59 @@
...
+
+// interaction test for creating volume
+describe('the create button in create volume page', () => {
+  it('should be enabled and the Add button should be disabled when no labels is specified', () => {
+    cy.findByRole('button', { name: /create/i }).should('be.enabled');
+    cy.findByRole('button', { name: /add/i }).should('be.disabled');
+  });
+
+  it('should be disabled before adding the valid label', () => {
+    cy.get('input[name=labelName]').type(VOLUME_LABEL_NAME);
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: it could be replaced with findByRole('textbox', {name: /Enter label name/i})

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+    cy.get('input[name=labelValue]').type(VOLUME_LABEL_VALUE);
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: it could be replaced with findByRole('textbox', {name: /Enter label value/i})

File: ui/cypress/integration/volume/createvolume.spec.js [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+
+    cy.findByRole('button', { name: /create/i }).should('be.disabled');
+    cy.findByRole('button', { name: /add/i }).should('be.enabled');
+  });
+
+  it('should be disabled as well as the Add button if labelName is not valid', () => {
+    cy.get('input[name=labelName]').type(VOLUME_LABEL_INVALID);
+    cy.get('input[name=labelValue]').type(VOLUME_LABEL_VALUE);
```
Comment (JBWatenbergScality) [inline ui/cypress/integration/volume/createvolume.spec.js]: same here

File: ui/cypress/integration/volume/createvolume.spec.js (hunk 10 above)
Comment (ChengYanJin) [reply ui/cypress/integration/volume/createvolume.spec.js]: OK. Maybe` cy.findByPlaceholderText(/Enter label name/i).` would be even better!

**Review by JBWatenbergScality — APPROVED** [review]
