### PR TITLE
[UI] Fix pod status display issue and the error for fetchNodeStats cancellation 

### LINKED ISSUE #2847: [UI] Pod status doesn't display correctly
**Component**: ui, nodes

**What happened**:
According to the [Pod-lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/) we should have the following possible values for the status of Pod: 
Pending, Running, Succeeded, Failed, Unknown

**What was expected**:

We have the following possible status of `Pod`
- Pod Running + All Containers are Running => **Green**
- Pod Running + At least one container is running => **Orange**
- Pod Pending => **Orange**
- Pod Succeeded => **Green**
- Pod Failed => **Red**
- Pod Unknown => **Red**

> Once the scheduler assigns a Pod to a Node, the kubelet starts creating containers for that Pod using a container runtime. There are three possible container states: Waiting, Running, and Terminated.
``` JSON
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2020-10-12T07:19:10.000Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2020-10-12T07:19:20.000Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2020-10-12T07:19:20.000Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2020-10-12T07:19:10.000Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://15e0e160a8de417444f5004bfb4a2c54611f25bdacd1cb957edf3a9e350ab738",
      "image": "docker.io/library/nginx:1.15.8",
      "imageID": "metalk8s-registry-from-config.invalid/metalk8s-2.6.0-dev/nginx@sha256:5b49c8e2c890fbb0a35f6050ed3c5109c5bb47b9e774264f4f3aa85bb69e2033",
      "lastState": {
        "terminated": {
          "containerID": "containerd://08281cc766b2a263bb93d7787022488d670d9cfd07f2929b51c6ca72614e3121",
          "exitCode": 255,
          "finishedAt": "2020-10-12T07:19:07.000Z",
          "reason": "Unknown",
          "startedAt": "2020-10-05T07:24:13.000Z"
        }
      },
      "name": "nginx",
      "ready": true,
      "restartCount": 19,
      "state": {
        "running": {
          "startedAt": "2020-10-12T07:19:13.000Z"
        }
      }
    }
  ],
  "hostIP": "192.168.1.18",
  "phase": "Running",
  "podIP": "192.168.1.18",
  "qosClass": "Burstable",
  "startTime": "2020-10-12T07:19:10.000Z"
}
```

In order to get the status of the `Container`, we need to check the state of the `containerStatuses` 

**Steps to reproduce**

**Resolution proposal** (optional):

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: ui

**Context**:  
There are 2 bugs:
- The status of the pod didn't display correctly. 
- The cancellation of the fetchNodeStats throw error in `watchRefreshNodeStats`

**Summary**:
Worked on the color specification for Pod status, please see:

- Pod Running + All Containers are Running => **Green**
- Pod Running + At least one container is running => **Orange**
- Pod Pending => **Orange**
- Pod Succeeded => **Green**
- Pod Failed => **Red**
- Pod Unknown => **Red**

**Acceptance criteria**: 
image

---

Closes: #2847

### CODE REVIEW

File: ui/src/ducks/app/monitoring.js [hunk 1]
```diff
@@ -770,7 +770,7 @@ export function* watchRefreshNodeStats() {
   while (true) {
     yield take(REFRESH_NODESTATS);
     while (true) {
-      yield fork(fetchNodeStats);
+      const fetchNodeStatsTask = yield fork(fetchNodeStats);
```
Comment (gdemonet) [inline ui/src/ducks/app/monitoring.js:773]: Whoops, didn't know about this, good catch! :+1:

File: ui/src/services/PodUtils.js [hunk 2]
```diff
@@ -8,16 +9,21 @@ export const getPodsListData = (nodeName, pods) => {
     podsList?.map((pod) => {
       const age = fromMilliSectoAge(new Date() - pod.startTime);
 
-      const numContainer = pod?.containerStatuses?.length;
-      const containerReady =
-        pod?.containerStatuses?.filter((pCS) => pCS.ready === true) ?? [];
+      const numContainer =
+        pod.status === STATUS_RUNNING ? pod?.containerStatuses?.length : 0;
```
Comment (gdemonet) [inline ui/src/services/PodUtils.js]: There's a small chance that you get `undefined` out of this:

```suggestion
        pod.status === STATUS_RUNNING
        ? (pod?.containerStatuses?.length ?? 0)
        : 0;
```

Comment (gdemonet) [reply ui/src/services/PodUtils.js]: Side-note: you can also determine the number of expected containers by looking at `pod.spec.containers.length`

**Review by gdemonet — DISMISSED** [review]
Really minor comment, feel free to ignore

**Comment by gdemonet** [comment]
I'm just a bit surprised: is your screenshot from a properly functioning platform? Having `Failed` pods that are older than a week seems strange, somehow they weren't GC'ed?

EDIT: just read [the docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection), and it seems like no, Failed pods are only GC'ed once there are more than some configured threshold in `k-c-m`. Interestingly, `kubectl get pods` has been hiding these by default (unless `-a` is passed) since 2015 :sweat_smile:  - see kubernetes/kubernetes#12102 - so maybe we should do the same? WDYT @thomasdanan @scality/metalk8s?

File: ui/src/services/PodUtils.js (hunk 2 above)
Comment (ChengYanJin) [reply ui/src/services/PodUtils.js]: Indeed!!! I may get `undefined` for `numContainer`. So I made the following changes.

```javascript
const numContainer = pod?.containerStatuses?.length ?? 0;
```

I didn't use the `pod.spec.containers.length` because I'll need to retrieve one more field and store it in redux store. Since I we already have `containerStatuses` and the length should be the same as `pod.spec.containers.length`

**Review by gdemonet — APPROVED** [review]

**Comment by thomasdanan** [comment]
> I'm just a bit surprised: is your screenshot from a properly functioning platform? Having `Failed` pods that are older than a week seems strange, somehow they weren't GC'ed?
> 
> EDIT: just read [the docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection), and it seems like no, Failed pods are only GC'ed once there are more than some configured threshold in `k-c-m`. Interestingly, `kubectl get pods` has been hiding these by default (unless `-a` is passed) since 2015 😅 - see [kubernetes/kubernetes#12102](https://github.com/kubernetes/kubernetes/issues/12102) - so maybe we should do the same? WDYT @thomasdanan @scality/metalk8s?

So yes, those pods are with status MatchNodeSelector and are there following a platform reboot and I don't know when they will be GCs but to me it could confuse the admin. 

Also, I can see those pods without using the -a option.
