### PR TITLE
UI : Move components to core UI

### LINKED ISSUE #1815: UIs: Move common Components and Styles to core-ui
**Component**: UI

**Why this is needed**:
We currently have some component/styles in MetalK8s UI that should be moved to core-ui.

**What should be done**:

This is a list of components: 
- (Remove/No need to handle it anymore) 
~~ui/src/components/CircleStatus.js (https://github.com/scality/metalk8s/issues/1247)~~
~~Move the component to core-ui.~~
@Cuervino can you please put the new design for the unknown status here (solid circle with gray color)
Update: We won't need this in core-ui anymore. We will hangle the status of the icon with all other Resources icon in Metalk8s. 

- ui/src/components/Loader.js
Merge the style with the `<Loader/>` component already in core-ui.
- ui/src/components/EmptyState.js
Move the component to core-ui.
- Move the style of empty table HeadRow to core-ui, maybe naming `<EmptyTable/>`
we currently have different styles when the table is empty. Please unify with this one, including
  - A separation line between title and content
  - The font color should be changed to `#B5B5B5`
image

   And replace the following components with the new styling component
   - NodeListTable
   - NodePageAlertsTabs
   - NodePartitionTable
   - VolumeLisTable
   - VolumeAlertTab
   
```js
        <Body {...getTableBodyProps()}>
          {rows.length === 0 ? (
            <HeadRow
              style={{
                width: '100%',
                paddingTop: padding.base,
                height: '60px',
              }}
            >
              <td
                style={{
                  textAlign: 'center',
                  background: theme.brand.primary,
                }}
              >
                {intl.translate('no_node_found')}
              </td>
            </HeadRow>
          ) : null}
```

**Implementation proposal** (strongly recommended):

**Test plan**:
After moving the component/styling to core-ui, please remove the code in MetalK8s and make sure there is no regression.

### PR DESCRIPTION
**Pull request by alexis-ld**
**Component**:
ui, nodes, volumes, alerts

**Context**: 
We want to move some common custom components to core-ui to uniformize the use.

**Summary**:
EmptyTable: Component to display when no data are in tables
EmptyState: Component for empty ressources pages (includes button and custom icon)
Loader: Updated current Loader component to add a "centered" prop to avoid creating wrappers to center it in each app.

To make this work we need to merge https://github.com/scality/core-ui/pull/251 first and use this version of core-ui.

**Acceptance criteria**: 
The above components are no longer custom defined in metal and are imported from core-ui instead.

---

Closes: #1815

### CODE REVIEW

File: ui/src/components/VolumeAlertsTab.js [hunk 1]
```diff
@@ -163,22 +163,7 @@ const ActiveAlertsCard = (props) => {
             </HeadRow>
           )}
           {PVCName && data?.length === 0 && (
```
Comment (ChengYanJin) [inline ui/src/components/VolumeAlertsTab.js:148]: We should also use the `<EmptyTable/>` to display the  {intl.translate('volume_is_not_bound')}
``` js
        {!PVCName && (
            <HeadRow
              style={{
                width: '100%',
                paddingTop: padding.base,
                height: '60px',
              }}
            >
              <td
                style={{
                  textAlign: 'center',
                  background: theme.brand.primary,
                }}
              >
                {intl.translate('volume_is_not_bound')}
              </td>
            </HeadRow>
          )}
```

File: ui/src/components/VolumeListTable.js [hunk 2]
```diff
@@ -324,25 +324,7 @@ function Table({
...
-                }}
-                className="td"
-              >
-                {intl.translate('no_volume_found')}
-              </div>
-            </div>
+            <EmptyTable>{intl.translate('no_volume_found')}</EmptyTable>
           ) : null}
           {/* <AutoSizer> is a <div/> so it breaks the table layout, 
           we need to use <div/> for all the parts of table(thead, tbody, tr, td...) and retrieve the defaullt styles by className. */}
```
Comment (ChengYanJin) [inline ui/src/components/VolumeListTable.js:332]: I indeed got a warning from the console. I probably need to change the `< EmptyTable/>` to a div. 

```
index.js:1 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>.
    in tr (created by styled.tr)
```

**Review by ChengYanJin — CHANGES_REQUESTED** [review]

**Review by ChengYanJin — APPROVED** [review]
